// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/audio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AudioService_GetAudioSegments_FullMethodName    = "/audio.AudioService/GetAudioSegments"
	AudioService_StreamAudio_FullMethodName         = "/audio.AudioService/StreamAudio"
	AudioService_UpdateSegmentLabels_FullMethodName = "/audio.AudioService/UpdateSegmentLabels"
	AudioService_Ping_FullMethodName                = "/audio.AudioService/Ping"
	AudioService_GetAudioQueue_FullMethodName       = "/audio.AudioService/GetAudioQueue"
)

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	// Get audio segments for a specific recording
	GetAudioSegments(ctx context.Context, in *GetAudioSegmentsRequest, opts ...grpc.CallOption) (*GetAudioSegmentsResponse, error)
	// Stream audio file data
	StreamAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (AudioService_StreamAudioClient, error)
	// Update segment labels
	UpdateSegmentLabels(ctx context.Context, in *UpdateSegmentLabelsRequest, opts ...grpc.CallOption) (*UpdateSegmentLabelsResponse, error)
	// Ping server
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetAudioQueue(ctx context.Context, in *GetAudioQueueRequest, opts ...grpc.CallOption) (*GetAudioQueueResponse, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) GetAudioSegments(ctx context.Context, in *GetAudioSegmentsRequest, opts ...grpc.CallOption) (*GetAudioSegmentsResponse, error) {
	out := new(GetAudioSegmentsResponse)
	err := c.cc.Invoke(ctx, AudioService_GetAudioSegments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) StreamAudio(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (AudioService_StreamAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_StreamAudio_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceStreamAudioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AudioService_StreamAudioClient interface {
	Recv() (*AudioResponse, error)
	grpc.ClientStream
}

type audioServiceStreamAudioClient struct {
	grpc.ClientStream
}

func (x *audioServiceStreamAudioClient) Recv() (*AudioResponse, error) {
	m := new(AudioResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *audioServiceClient) UpdateSegmentLabels(ctx context.Context, in *UpdateSegmentLabelsRequest, opts ...grpc.CallOption) (*UpdateSegmentLabelsResponse, error) {
	out := new(UpdateSegmentLabelsResponse)
	err := c.cc.Invoke(ctx, AudioService_UpdateSegmentLabels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AudioService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) GetAudioQueue(ctx context.Context, in *GetAudioQueueRequest, opts ...grpc.CallOption) (*GetAudioQueueResponse, error) {
	out := new(GetAudioQueueResponse)
	err := c.cc.Invoke(ctx, AudioService_GetAudioQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility
type AudioServiceServer interface {
	// Get audio segments for a specific recording
	GetAudioSegments(context.Context, *GetAudioSegmentsRequest) (*GetAudioSegmentsResponse, error)
	// Stream audio file data
	StreamAudio(*AudioRequest, AudioService_StreamAudioServer) error
	// Update segment labels
	UpdateSegmentLabels(context.Context, *UpdateSegmentLabelsRequest) (*UpdateSegmentLabelsResponse, error)
	// Ping server
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetAudioQueue(context.Context, *GetAudioQueueRequest) (*GetAudioQueueResponse, error)
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServiceServer struct {
}

func (UnimplementedAudioServiceServer) GetAudioSegments(context.Context, *GetAudioSegmentsRequest) (*GetAudioSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioSegments not implemented")
}
func (UnimplementedAudioServiceServer) StreamAudio(*AudioRequest, AudioService_StreamAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedAudioServiceServer) UpdateSegmentLabels(context.Context, *UpdateSegmentLabelsRequest) (*UpdateSegmentLabelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSegmentLabels not implemented")
}
func (UnimplementedAudioServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAudioServiceServer) GetAudioQueue(context.Context, *GetAudioQueueRequest) (*GetAudioQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioQueue not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_GetAudioSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).GetAudioSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_GetAudioSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).GetAudioSegments(ctx, req.(*GetAudioSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).StreamAudio(m, &audioServiceStreamAudioServer{stream})
}

type AudioService_StreamAudioServer interface {
	Send(*AudioResponse) error
	grpc.ServerStream
}

type audioServiceStreamAudioServer struct {
	grpc.ServerStream
}

func (x *audioServiceStreamAudioServer) Send(m *AudioResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AudioService_UpdateSegmentLabels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSegmentLabelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).UpdateSegmentLabels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_UpdateSegmentLabels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).UpdateSegmentLabels(ctx, req.(*UpdateSegmentLabelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_GetAudioQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).GetAudioQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_GetAudioQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).GetAudioQueue(ctx, req.(*GetAudioQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAudioSegments",
			Handler:    _AudioService_GetAudioSegments_Handler,
		},
		{
			MethodName: "UpdateSegmentLabels",
			Handler:    _AudioService_UpdateSegmentLabels_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AudioService_Ping_Handler,
		},
		{
			MethodName: "GetAudioQueue",
			Handler:    _AudioService_GetAudioQueue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _AudioService_StreamAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/audio.proto",
}
